### ISSUE TITLE
US17: Overall Styling

### ISSUE THREAD

**Issue by JudithRe** [JudithRe/capstone-flashcard-dictionary#39]
## Value proposition

As a student
I want to use the app with intuitive styling
in order to find my way around

## Acceptance criteria

- [ ] first basic styling is implemented throughout the app 

## Tasks

- [ ] review all components and update styling to be consistent

Size: S/M

**Comment by CJAkkuec** [comment]
I think this might be a dev ticket and not a user story. A dev ticket is just plain tasks that describe what needs to be done, because there is no user benefit/value beyond "looks nice". 😂
